### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by ralphtheninja** [mbinot/sails-leveldb#2]
![screenshot from 2015-03-21 23 02 14](https://cloud.githubusercontent.com/assets/308049/6767022/57881a9a-d01e-11e4-8766-1ab689885f36.png)

Someone should have a look at this :) Not sure what's going on. I'd probably rewrite the tests from scratch using something more simple, like `tape`.

/cc @tjwebb

**Comment by tjwebb** [comment]
There are many hundreds of tests in the full adapter suite; I have no idea why you'd want to re-write that stuff.

Which tests are failing?

**Comment by ralphtheninja** [comment]
@tjwebb Ok, rewriting is not the solution. There are 70 tests failing. Not going to list them here.

**Comment by BlessYAHU** [comment]
Is this why it is not listed in the npm registry anymore?

**Comment by mbinot** [comment]
Probably, yes. The adapter needs to be migrated to the current waterline version, but I honestly can not tell when I might find time to work on it.

**Comment by BlessYAHU** [comment]
can you tell me if the [repository url in the package.json](https://github.com/mbinot/sails-leveldb/blob/master/package.json#L11) is right?  I might see if I can fork this, but am having issues npm installing (malformed URI).

**Comment by mbinot** [comment]
the package seems to be ok, i think. did you try a 'rm -rf node_modules' before 'npm install'?
